name: Flatris rulez
on: [push]

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        node: [10, 12, 14]
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn --frozen-lockfile
      - run: yarn flow check
      - run: yarn lint
      - run: yarn test --maxWorkers=2
